# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
#symbol = "âœ"     # The "symbol" segment is being set to "âœ"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[env_var.GK]
variable = "GK_PROFILE"
symbol = "ğŸ”"
style = "bright-red"
format = "with [$symbol $env_value]($style)"

[env_var.L0]
variable = "LAYER0_PROFILE"
symbol = "âˆ"
style = "bright-white"
format = "with [$symbol $env_value]($style) "

[docker_context]
disabled = true

[status]
disabled = false

[env_var.KUBECTX]
variable = "KUBECTL_PROFILE"
symbol = "âˆ"
style = "bright-white"
format = "with [$symbol $env_value]($style) "